# Generated by Django 5.1.1 on 2024-09-29 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_system', '0002_remove_cfproblem_contest_remove_cfsubmission_cf_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cfuser',
            name='handle',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
