# Generated by Django 4.2.16 on 2024-09-28 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CFContest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('difficulty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CFProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemset_name', models.CharField(max_length=255)),
                ('index', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('points', models.FloatField()),
                ('rating', models.IntegerField()),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_system.cfcontest')),
            ],
        ),
        migrations.CreateModel(
            name='CFUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=255)),
                ('rank', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CFUserAndContest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_type', models.CharField(choices=[('CONTESTANT', 'CONTESTANT'), ('PRACTICE', 'PRACTICE'), ('VIRTUAL', 'VIRTUAL'), ('MANAGER', 'MANAGER'), ('OUT_OF_COMPETITION', 'OUT_OF_COMPETITION')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CFSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cf_id', models.IntegerField()),
                ('creation_time', models.IntegerField()),
                ('verdict', models.CharField(blank=True, choices=[('FAILED', 'FAILED'), ('OK', 'OK'), ('PARTIAL', 'PARTIAL'), ('COMPILATION_ERROR,', 'COMPILATION_ERROR,'), ('RUNTIME_ERROR', 'RUNTIME_ERROR'), ('WRONG_ANSWER', 'WRONG_ANSWER'), ('PRESENTATION_ERROR', 'PRESENTATION_ERROR'), ('TIME_LIMIT_EXCEEDED', 'TIME_LIMIT_EXCEEDED'), ('MEMORY_LIMIT_EXCEEDED', 'MEMORY_LIMIT_EXCEEDED'), ('IDLENESS_LIMIT_EXCEEDED', 'IDLENESS_LIMIT_EXCEEDED'), ('SECURITY_VIOLATED', 'SECURITY_VIOLATED'), ('CRASHED', 'CRASHED'), ('INPUT_PREPARATION_CRASHED', 'INPUT_PREPARATION_CRASHED'), ('CHALLENGED', 'CHALLENGED'), ('SKIPPED', 'SKIPPED'), ('TESTING', 'TESTING'), ('REJECTED', 'REJECTED')], max_length=255, null=True)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_system.cfcontest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_system.cfproblem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_system.cfuser')),
            ],
        ),
        migrations.CreateModel(
            name='CFRatingChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('old_rating', models.IntegerField()),
                ('new_rating', models.IntegerField()),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_system.cfcontest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_system.cfuser')),
            ],
        ),
        migrations.CreateModel(
            name='CFProblemAndTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_system.cfproblem')),
            ],
        ),
    ]
